program Melomaniac;

uses
  System.StartUpCopy,
  FMX.Forms,
  MelomaniacUnit in 'MelomaniacUnit.pas' {MainForm},
  FMX.SingleSoundUnit in '..\FMX.SingleSoundUnit.pas',
  ThreadFactoryUnit in '..\ThreadFactoryUnit.pas',
  ThreadRegistryUnit in '..\ThreadRegistryUnit.pas',
  FMX.FormExtUnit in '..\FMX.FormExtUnit.pas',
//  FMX.FormExt.Types in '..\FMX.FormExt.Types.pas',
  ThreadFactoryRegistryUnit in '..\ThreadFactoryRegistryUnit.pas',
  ObjectRegistryUnit in '..\ObjectRegistryUnit.pas',
  PlayListUnit in 'PlayListUnit.pas',
  LockedListExtUnit in '..\LockedListExtUnit.pas',
  StringToolsUnit in '..\StringToolsUnit.pas',
  PlayControllerUnit in 'PlayControllerUnit.pas',
  StateUnit in 'StateUnit.pas',
  ConstantsUnit in 'ConstantsUnit.pas',
  FMX.MultiResBitmapExtractorUnit in '..\FilePacker\FMX.MultiResBitmapExtractorUnit.pas',
  FMX.MultiResBitmapsUnit in '..\FMX.MultiResBitmapsUnit.pas',
  VisualSchemeUnit in 'VisualSchemeUnit.pas',
  FilePackerUnit in '..\FilePacker\FilePackerUnit.pas',
  FMX.ControlToolsUnit in '..\FMX.ControlToolsUnit.pas',
  BitmapStorageUnit in 'BitmapStorageUnit.pas',
  ToolsUnit in 'ToolsUnit.pas',
  FMX.PopupMenuExt in '..\FMX.PopupMenuExt\FMX.PopupMenuExt.pas',
  FMX.PopupMenuExt.BaseClass in '..\FMX.PopupMenuExt\FMX.PopupMenuExt.BaseClass.pas',
  FMX.PopupMenuExt.Constants in '..\FMX.PopupMenuExt\FMX.PopupMenuExt.Constants.pas',
  PopupMenuExt.Item in '..\FMX.PopupMenuExt\PopupMenuExt.Item.pas',
  FMX.PopupMenuExt.Form in '..\FMX.PopupMenuExt\FMX.PopupMenuExt.Form.pas',
  FMX.PopupMenuExt.Layout in '..\FMX.PopupMenuExt\FMX.PopupMenuExt.Layout.pas',
  FMX.PopupMenuExt.Thread in '..\FMX.PopupMenuExt\FMX.PopupMenuExt.Thread.pas',
  FMX.PopupMenuExt.Windows in '..\FMX.PopupMenuExt\FMX.PopupMenuExt.Windows.pas',
  FMX.Theme in '..\FMX.Theme\FMX.Theme.pas',
  FMX.Theme.Types in '..\FMX.Theme\FMX.Theme.Types.pas',
  DebugUnit in '..\DebugUnit.pas',
  FileToolsUnit in '..\FileToolsUnit.pas',
  AudioFormatDetectorUnit in 'AudioFormatDetectorUnit.pas',
  BaseDBAccessUnit in '..\SQL\BaseDBAccessUnit.pas',
  DBToolsUnit in '..\SQLite\DBToolsUnit.pas',
  SQLTemplatesUnit in '..\SQL\SQLTemplatesUnit.pas',
  TextExtractorUnit in '..\FilePacker\TextExtractorUnit.pas',
  DBExceptionContainerUnit in '..\SQL\DBExceptionContainerUnit.pas',
  DBAccessUnit in 'DBAccessUnit.pas',
  FlacTAGReaderUnit in 'TAGReaders\FlacTAGReaderUnit.pas',
  MP3TAGsReaderUnit in 'TAGReaders\MP3TAGsReaderUnit.pas',
  OGGTAGReaderUnit in 'TAGReaders\OGGTAGReaderUnit.pas',
  TAGReaderThreadUnit in 'TAGReaders\TAGReaderThreadUnit.pas',
  WAVTAGReaderUnit in 'TAGReaders\WAVTAGReaderUnit.pas',
  FMX.HintFormUnit in '..\FMX.Hint\FMX.HintFormUnit.pas',
  FMX.HintThreadUnit in '..\FMX.Hint\FMX.HintThreadUnit.pas',
  FMX.HintUnit in '..\FMX.Hint\FMX.HintUnit.pas',
  FMX.TrayIcon.Win in '..\FMX.TrayIcon.Win.pas',
  BorderFrameUnit in 'FMX.BorderFrame\BorderFrameUnit.pas' {BorderFrame: TFrame},
  FMX.ImageToolsUnit in '..\FMX.ImageToolsUnit.pas',
  TimelineTrackerThreadUnit in 'Threads\TimelineTrackerThreadUnit.pas',
  HeighlightFailThreadUnit in 'Threads\HeighlightFailThreadUnit.pas',
  PlayListFormUnit in 'PlayListForm\PlayListFormUnit.pas' {PlayListForm},
  PlayListItemFrameUnit in 'PlayListForm\PlayListItemFrameUnit.pas' {PlayListItemFrame: TFrame},
  BaseMouseHandlersUnit in 'MouseHandlers\BaseMouseHandlersUnit.pas',
  MainFormMouseHandlersUnit in 'MouseHandlers\MainFormMouseHandlersUnit.pas',
  PlayListFormMouseHandlersUnit in 'MouseHandlers\PlayListFormMouseHandlersUnit.pas',
  ParamsExtUnit in '..\ParamsExt\ParamsExtUnit.pas',
  BinFileTypes in '..\Types\BinFileTypes.pas',
  StreamHandler in '..\Stream\StreamHandler.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TMainForm, MainForm);
  Application.Run;
end.
