program Melomaniac;

uses
  System.StartUpCopy,
  FMX.Forms,
  MelomaniacUnit in 'MelomaniacUnit.pas' {MainForm},
  FMX.SingleSoundUnit in '..\DevelopmentsCollection\FMX.SingleSoundUnit.pas',
  ThreadFactoryUnit in '..\DevelopmentsCollection\ThreadFactoryUnit.pas',
  ThreadRegistryUnit in '..\DevelopmentsCollection\ThreadRegistryUnit.pas',
  ParamsExtUnit in '..\DevelopmentsCollection\ParamsExtUnit.pas',
  FMX.FormExtUnit in '..\DevelopmentsCollection\FMX.FormExtUnit.pas',
  ThreadFactoryRegistryUnit in '..\DevelopmentsCollection\ThreadFactoryRegistryUnit.pas',
  ObjectRegistryUnit in '..\DevelopmentsCollection\ObjectRegistryUnit.pas',
  PlayListUnit in 'PlayListUnit.pas',
  LockedListExtUnit in '..\DevelopmentsCollection\LockedListExtUnit.pas',
  StringToolsUnit in '..\DevelopmentsCollection\StringToolsUnit.pas',
  PlayControllerUnit in 'PlayControllerUnit.pas',
  StateUnit in 'StateUnit.pas',
  ConstantsUnit in 'ConstantsUnit.pas',
  FMX.MultiResBitmapExtractorUnit in '..\DevelopmentsCollection\FilePacker\FMX.MultiResBitmapExtractorUnit.pas',
  FMX.MultiResBitmapsUnit in '..\DevelopmentsCollection\FMX.MultiResBitmapsUnit.pas',
  VisualSchemeUnit in 'VisualSchemeUnit.pas',
  FilePackerUnit in '..\DevelopmentsCollection\FilePacker\FilePackerUnit.pas',
  FMX.ControlToolsUnit in '..\DevelopmentsCollection\FMX.ControlToolsUnit.pas',
  BitmapStorageUnit in 'BitmapStorageUnit.pas',
  ToolsUnit in 'ToolsUnit.pas',
  FMX.PopupMenuExt in '..\DevelopmentsCollection\FMX.PopupMenuExt\FMX.PopupMenuExt.pas',
  FMX.PopupMenuExt.BaseClass in '..\DevelopmentsCollection\FMX.PopupMenuExt\FMX.PopupMenuExt.BaseClass.pas',
  FMX.PopupMenuExt.Constants in '..\DevelopmentsCollection\FMX.PopupMenuExt\FMX.PopupMenuExt.Constants.pas',
  PopupMenuExt.Item in '..\DevelopmentsCollection\FMX.PopupMenuExt\PopupMenuExt.Item.pas',
  FMX.PopupMenuExt.Form in '..\DevelopmentsCollection\FMX.PopupMenuExt\FMX.PopupMenuExt.Form.pas',
  FMX.PopupMenuExt.Layout in '..\DevelopmentsCollection\FMX.PopupMenuExt\FMX.PopupMenuExt.Layout.pas',
  FMX.PopupMenuExt.Thread in '..\DevelopmentsCollection\FMX.PopupMenuExt\FMX.PopupMenuExt.Thread.pas',
  FMX.PopupMenuExt.Windows in '..\DevelopmentsCollection\FMX.PopupMenuExt\FMX.PopupMenuExt.Windows.pas',
  FMX.ThemeUnit in '..\DevelopmentsCollection\FMX.ThemeUnit.pas',
  DebugUnit in '..\DevelopmentsCollection\DebugUnit.pas',
  FileToolsUnit in '..\DevelopmentsCollection\FileToolsUnit.pas',
  AudioFormatDetectorUnit in 'AudioFormatDetectorUnit.pas',
  BaseDBAccessUnit in '..\DevelopmentsCollection\SQL\BaseDBAccessUnit.pas',
  DBToolsUnit in '..\DevelopmentsCollection\SQLite\DBToolsUnit.pas',
  SQLTemplatesUnit in '..\DevelopmentsCollection\SQL\SQLTemplatesUnit.pas',
  TextExtractorUnit in '..\DevelopmentsCollection\FilePacker\TextExtractorUnit.pas',
  DBExceptionContainerUnit in '..\DevelopmentsCollection\SQL\DBExceptionContainerUnit.pas',
  DBAccessUnit in 'DBAccessUnit.pas',
  FlacTAGReaderUnit in 'TAGReaders\FlacTAGReaderUnit.pas',
  MP3TAGsReaderUnit in 'TAGReaders\MP3TAGsReaderUnit.pas',
  OGGTAGReaderUnit in 'TAGReaders\OGGTAGReaderUnit.pas',
  TAGReaderThreadUnit in 'TAGReaders\TAGReaderThreadUnit.pas',
  WAVTAGReaderUnit in 'TAGReaders\WAVTAGReaderUnit.pas',
  FMX.HintFormUnit in '..\DevelopmentsCollection\FMX.Hint\FMX.HintFormUnit.pas',
  FMX.HintThreadUnit in '..\DevelopmentsCollection\FMX.Hint\FMX.HintThreadUnit.pas',
  FMX.HintUnit in '..\DevelopmentsCollection\FMX.Hint\FMX.HintUnit.pas',
  FMX.TrayIcon.Win in '..\DevelopmentsCollection\FMX.TrayIcon.Win.pas',
  BorderFrameUnit in '..\DevelopmentsCollection\BorderFrame\BorderFrameUnit.pas' {BorderFrame: TFrame},
  FMX.ImageToolsUnit in '..\DevelopmentsCollection\FMX.ImageToolsUnit.pas',
  BorderFrameTypesUnit in '..\DevelopmentsCollection\BorderFrame\BorderFrameTypesUnit.pas',
  TimelineTrackerThreadUnit in 'Threads\TimelineTrackerThreadUnit.pas',
  HeighlightFailThreadUnit in 'Threads\HeighlightFailThreadUnit.pas',
  PlayListFormUnit in 'PlayListForm\PlayListFormUnit.pas' {PlayListForm},
  PlayListItemFrameUnit in 'PlayListForm\PlayListItemFrameUnit.pas' {PlayListItemFrame: TFrame},
  BaseMouseHandlersUnit in 'MouseHandlers\BaseMouseHandlersUnit.pas',
  MainFormMouseHandlersUnit in 'MouseHandlers\MainFormMouseHandlersUnit.pas',
  PlayListFormMouseHandlersUnit in 'MouseHandlers\PlayListFormMouseHandlersUnit.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TMainForm, MainForm);
  Application.Run;
end.
